version: 2
jobs:
  test:
    docker:
      - image: ocaml/opam2:debian-10-ocaml-4.08
    environment:
      - TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "bolt.opam" }}
      - run:
          name: "Install deps"
          command: sudo apt-get install -y m4 && make install
      - save_cache:
          key: cache-{{ checksum "bolt.opam" }}
          paths:
            - ~/.opam
      - run:
          name: "Lint"
          command: opam exec -- make lint
      - run:
          name: "Test"
          command: opam exec -- make test
      - run:
          name: "Calculate Coverage"
          command: opam exec -- make coverage
      - run:
          name: "Send Coveralls.io coverage report"
          command: opam exec -- bisect-ppx-report send-to Coveralls
workflows:
  version: 2
  build:
    jobs:
      - test
